name: libra-one-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - openmc
  - ipykernel
  - nbconvert
  - vtk
  - pip
  - pip:
    - libra-toolbox>=0.6
    - openmc_data_downloader