name: libra-one-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.10
  - openmc
  - ipykernel
  - nbconvert
  - vtk
  - python-gmsh
  - festim=2.0a2
  - pyvista
  - pip
  - pip:
    - libra-toolbox>=0.6
    - openmc_data_downloader
    - git+https://github.com/festim-dev/openmc2dolfinx